# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-14 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20181113_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', max_length=50, upload_to='teacher/%Y/%m', verbose_name='讲师头像'),
        ),
    ]
